language: c

os:
  - linux

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - liblua5.2-dev
      - libssl-dev
      - liblzo2-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
