language: c

os:
  - linux

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install lua5.2-dev lua-posix lua-luaossl lua-cqueues libssl-dev liblzo2-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make
